### ISSUE TITLE
set localecho

### ISSUE THREAD

**Issue by MichaelJWells** [ytang/welly#1]
Dear Welly Admins,

There ought to be a way to set localecho in Welly so that a user can see the text typed in when using welly as a telnet client. 

At present the text typed in is not visible and one is unable to check for typo errors in the commands that are entered into telnet. In a windows telnet the following help file is the usual procedure, but on Mac this does not seem to work:

help telnet_echo
SYNOPSIS:
  For telnet users, the following commands are used to change echo in telnet,
  so you can choose to either see, or not to see, what you are typing while
  you type it. To remedy this (turn echo on), follow these steps:
    1. Connect to \<your-favourite-MUD\> and log in with your name and password.
    2. Hit <Ctrl+]> (i.e. hold down the <Ctrl> key, then press the <]> key)
       This will drop you to the telnet prompt, looking something like this:
         Welcome to Microsoft Telnet Client
         Escape Character is 'CTRL+]'
         Microsoft Telnet>
    3. At this telnet prompt, type 'set localecho' and hit <Enter>:
         Microsoft Telnet> set localecho
         Local echo on
         Microsoft Telnet>
    4. At the resulting telnet prompt, hit <Enter> one more time to return
       to \<your-favourite-MUD\>.  You should now be able to see what you type as
       you type it. (To undo it, use 'unset localecho' or 'u localecho')
NOTE:
  1. In Windows 2000 and prior, you will need to type 'set local_echo'.
  2. If you fail to use the proper Ctrl commands and type 'set localecho on'
     the mud will tell you: 'Localecho is not a setable option.'

One possible coding solution that might be adapted to this problem was found on the following webpage: 
https://os.mbed.com/questions/6166/How-to-set-up-the-terminal-program-scree/

Also the following Internet RFC Telnet Echo Option webpage may provide more details about using this setting:
https://tools.ietf.org/html/rfc857

Yours,
MichaelJWells

**Comment by ytang** [comment]
Thanks for your comment. Welly is optimized for Chinese Bulletin Board Systems (BBS) and is never intended to be a full-fledged telnet client. As far as I know, all major BBS sites (e.g., MITBBS.com, NewSMTH.net, and PTT.cc) prohibit local echo. If you encounter any BBS site that requires local echo, please comment below, and I will take a look.

On the other hand, if you just need a generic telnet client, you can install one via [homebrew](https://formulae.brew.sh/formula/telnet).

**Comment by MichaelJWells** [comment]
Thank you for your reply. I did not know that BBS systems were still used much in the Internet age, at least not the old modem dial-up kind where bandwidth was so narrow and every byte counted and local echo was not allowed. I can see how BBS systems still might be a way of seeking out a way to communicate while avoiding the Internet in today's world of heavy surveillance. In any case, if your target is Chinese BBS and the telnet code is not intended to be a full telnet client then I understand why adding local echo would not be something you would like to implement. 

I do actually have a generic telnet client I installed via homebrew. I had been using it when an issue arose and I needed another telnet client to test it on my Mac. Welly was the only telnet client on the App store that would work for me out of the box and I was able to resolve my issue. Welly was not intended to replace my usual telnet client and was just for backup. 

Thank you for your response and best of luck to you and your BBS client. Just out of curiosity, do Chinese BBS get a lot of use and are they generally used via telnet or dial-up modem?

Yours, 
MichaelJWells

**Comment by ytang** [comment]
Thank you, and I'm glad that Welly helped you resolve your issue. I'm not going to add support for local echo because I don't see a convincing use case for now.

Chinese BBS sites have been around for over 25 years and have accumulated millions of loyal users. In addition to telnet, registered users can connect via SSH or WebSocket for better security, and some sites also offer web or mobile apps. If you're curious, you can try connecting to NewSMTH or MITBBS as a guest user. Unfortunately, everything is in Chinese, but I'll try my best to illustrate the process.

In Welly, please enter `bbs.newsmth.net` or `mitbbs.com` as the address. After being connected, the server will prompt you `请输入代号:`, which translates to `Please enter the user name:`. You can enter `guest` here, and no password is needed. After that, please press the `Enter` key several times to skip the welcome screens until you reach the main menu. (You can refer to [the screenshots of Welly on the Mac App Store](https://apps.apple.com/us/app/id1521402269).) From there, you can browse whatever the BBS has to offer using the arrow keys on your keyboard. Enjoy this 20th-century experience!
